package Hibernate;
// Generated 18-nov-2018 18:36:45 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Piezas generated by hbm2java
 */
public class Piezas implements java.io.Serializable {

	private String codigo;
	private String nombre;
	private float precio;
	private String descipcion;
	private Set<Gestion> gestions = new HashSet<Gestion>(0);

	public Piezas() {
	}

	public Piezas(String codigo, String nombre, float precio) {
		this.codigo = codigo;
		this.nombre = nombre;
		this.precio = precio;
	}

	public Piezas(String codigo, String nombre, float precio, String descipcion, Set<Gestion> gestions) {
		this.codigo = codigo;
		this.nombre = nombre;
		this.precio = precio;
		this.descipcion = descipcion;
		this.gestions = gestions;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public float getPrecio() {
		return this.precio;
	}

	public void setPrecio(float precio) {
		this.precio = precio;
	}

	public String getDescipcion() {
		return this.descipcion;
	}

	public void setDescipcion(String descipcion) {
		this.descipcion = descipcion;
	}

	public Set<Gestion> getGestions() {
		return this.gestions;
	}

	public void setGestions(Set<Gestion> gestions) {
		this.gestions = gestions;
	}

}
